### ISSUE TITLE
Add support for tfvars+tfstate

### ISSUE THREAD

**Issue by radeksimko** [alexlouden/Terraform.tmLanguage#1]
I haven't looked at the tmLanguage specification, but it would be nice to define some kind of mapping for the following:
- `*.tfvars` => `*.ini` (there may be some small differences in escaping, but I'd just ignore that for any first implementation)
- `*.tfstate` => `*.json`

btw. thanks again for the effort invested into this! :+1:

**Comment by alexlouden** [comment]
My pleasure :smiley: - happy to help. I don't have time to do any more on this for now, but the following should help whoever is keen:

Here are the docs I've been working from:

- http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html (official guide)
- https://manual.macromates.com/en/language_grammars (reference for naming things)

And I've been using the following Sublime packages:

- https://github.com/SublimeText/AAAPackageDev (official way of building YAML -> plist)
- https://github.com/facelessuser/ScopeHunter (inspect and see what's being matched)

And here are a few good examples:

- https://github.com/SublimeText/AAAPackageDev/tree/master/Syntax%20Definitions
- JSON: https://github.com/facelessuser/sublime-languages/blob/master/Better%20Javascript/JSON.tmLanguage
- INI: https://github.com/clintberry/sublime-text-2-ini/blob/master/INI.tmLanguage

**Comment by radeksimko** [comment]
> I don't have time to do any more on this for now

That's understandable, I chatted with a few folks from the Terraform core team about eventually moving this under `/hashicorp/Terraform.tmLanguage` and they said they're open, but only if there will be a guaranteed maintainer since not many people in Hashicorp use Sublime Text.

That said, I will probably send a few PRs to cover the above ^ and then eventually add this repo (`alexlouden/Terraform.tmLanguage`) to the official package repository (if you don't mind), so it's easier to find & install for anyone.

**Comment by alexlouden** [comment]
I've added you as a contributor - please feel free to make any changes/additions as you like! Very happy for it to be listed on package control - I was holding off to check you guys were ok with it.

**Comment by euforia** [comment]
@alexlouden: i've forked your code to start making it geared for hcl rather than terraform specifically.  https://github.com/euforia/HCL.tmLanguage

I've changed some of the snippet scopes which still need work and also add .hcl file extension.  

I wasn't sure what plan was for this project but was wondering if you were open to that idea and would be happy to contribute.

@radeksimko: if you don't mind me asking -  what is being used for HCL syntax highlighting ?

**Comment by radeksimko** [comment]
> I wasn't sure what plan was for this project but was wondering if you were open to that idea and would be happy to contribute.

Just linking a (positive) answer here: https://github.com/hashicorp/terraform/issues/2030#issuecomment-238076901

> if you don't mind me asking - what is being used for HCL syntax highlighting ?

Do you mean on github.com? We had a debate about what the short-term solution (language closest to HCL) should be and we ended up with Ruby, although JavaScript was also pretty close. None of those are ideal, so (I believe) there's an obvious interest in the community to eventually leverage repository like this in `github/linguist` to enable real HCL syntax highlighting on github.com.

https://github.com/github/linguist/pull/1899
https://github.com/github/linguist/pull/2527

If you were rather asking for definition/docs of HCL itself, the best source is probably https://github.com/hashicorp/hcl 😉

**Comment by alexlouden** [comment]
Hey @euforia / @radeksimko - as of #19 this repo now supports for the `.hcl` file extension. I've found some spare time and have been doing a [little more](https://github.com/alexlouden/Terraform.tmLanguage/pulse/monthly) on this project recently, and I'm keen to keep maintaining it with bugfixes/improvements going forward.

github/linguist#3392 has just been merged, which means this repo will be used for syntax highlighting `.hcl` and `.tf` on Github.com pretty soon (when linguist is next released). 🎉

**Comment by radeksimko** [comment]
@alexlouden That is great, I really appreciate the time you spent on this! 👍 🎉 

Can't wait for the next release of `linguist` :)

**Comment by alexlouden** [comment]
Looks like it's released! Not sure when it'll hit github.com

**Comment by alexlouden** [comment]
@radeksimko Yew!

![](http://i.giphy.com/9K2nFglCAQClO.gif)
