### ISSUE TITLE
Installing via package control does not provide snippets

### ISSUE THREAD

**Issue by ApsOps** [alexlouden/Terraform.tmLanguage#11]
I installed the package using package control. I did get the sytax highlighting but snippets seem to be missing. Am I missing something?

EDIT: Looks like it's 'cause there are commits that haven't been in a release yet. @alexlouden  Could you please create a new release? :)

**Comment by alexlouden** [comment]
Hey @ApsOps, sorry about the delay. I've created a [0.3.0 release](https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.3.0) - please let me know if you have any more issues!

**Comment by alexlouden** [comment]
I've also just created 0.4.0, which includes some changes from @Jonnymcc to fix bracket matching. Would you mind trying it out and letting me know if it works for you?

**Comment by ApsOps** [comment]
@alexlouden Just upgraded to 0.4.0. Works as expected 👍
