### ISSUE TITLE
path to sublime packages on Mac

### ISSUE THREAD

**Issue by davgibney1** [alexlouden/Terraform.tmLanguage#15]
In your readme, maybe you could specify different paths for different MacOSX versions. I'm on 10.11.6 and running Sublime 3, so my path to manually install your plugin was here:

/Applications/Sublime Text.app/Contents/MacOS/Packages

This path is different from what is on your readme.

Thanks!

**Comment by alexlouden** [comment]
Hey, thanks for the note!

I've had a look at the sublime text 3 [docs](https://www.sublimetext.com/docs/3/packages.html), and I think the path you mentioned is for **system** packages, e.g. the `HTML.sublime-package` that comes with Sublime Text. The folders mentioned in the README are the recommended location to install **user** packages.

The preferences menu is an easy way to get to the user packages folder:

![screen shot 2016-12-15 at 12 57 40 pm](https://cloud.githubusercontent.com/assets/1332954/21212324/79f95a5c-c2c6-11e6-988c-7fd38fb989b1.png)

Could you have a look on your machine - does this take you to the `~/Library/Application Support/Sublime Text 3/` folder? 
If so, the recommended location for this package is at `~/Library/Application Support/Sublime Text 3/Installed Packages/Terraform.sublime-package`. If the system packages folder works for you, that's fine, but there's a risk that when Sublime upgrades the Terraform package might get deleted.

Cheers,
Alex

**Comment by alexlouden** [comment]
Hey @davgibney1, I'm going to close this - hopefully my previous comment has resolved your issue!
