### ISSUE TITLE
Add support for variable names without quotes

### ISSUE THREAD

**Issue by dmlemos** [alexlouden/Terraform.tmLanguage#17]
Seems like there is no highlighting when variables don't have quotes around its definition.

**Variable with quotes:**
<img width="281" alt="sublime_highlight_tf_var" src="https://cloud.githubusercontent.com/assets/1868454/22700016/15b381f2-ed51-11e6-822c-98434512b1ae.png">

**Variable without quotes:**
<img width="267" alt="sublime_nohighlight_tf_var" src="https://cloud.githubusercontent.com/assets/1868454/22700063/3d13ec50-ed51-11e6-9ada-993ba41d2858.png">

**Comment by alexlouden** [comment]
Ah thanks for reporting this! I'll fix it and let you know when there's a new release out.

**Comment by alexlouden** [comment]
Hey @dmlemos - I've created a [new release](https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.8.0), hope it works for you!

![screen shot 2017-02-08 at 8 59 53 pm](https://cloud.githubusercontent.com/assets/1332954/22738417/562ca05a-ee42-11e6-90bd-fc4bd2b2ce7d.png)

**Comment by dmlemos** [comment]
Thanks @alexlouden. Do you know when it shows up in Package Control?

**Comment by alexlouden** [comment]
Package control should try and upgrade when Sublime starts, and then every 6 hours by default. You can also manually trigger an upgrade using the Command Pallet: Package Control --> Upgrade Package

See https://packagecontrol.io/docs/usage

**Comment by dmlemos** [comment]
Great! Got the update now.

**Comment by alexlouden** [comment]
Oh awesome, glad it updated!
