### ISSUE TITLE
Broken highlighting with nested interpolations

### ISSUE THREAD

**Issue by alex-aver** [alexlouden/Terraform.tmLanguage#18]
If you have a resource attribute with nested interpolations where you need to use quotes, the highlighting in the rest of the document breaks. It's easier to explain with examples:

The following statement breaks the highlighting:
`user_data = "${file("${path.module}/text_files/ec2/user_data_scripts/ecs_app")}"`

But if I removed a pair of quotes, highlighting works fine:
`user_data = "${file(${path.module}/text_files/ec2/user_data_scripts/ecs_app)}"`

Or, if I were to keep the quotes, but lose the `${path.module}`, highlighting works fine:
`user_data = "${file("text_files/ec2/user_data_scripts/ecs_app")}"`

![screen shot 2017-02-09 at 10 09 59 am](https://cloud.githubusercontent.com/assets/20953473/22789291/84eb7b96-eeb0-11e6-8ddb-ba4895251713.png)
![screen shot 2017-02-09 at 10 09 36 am](https://cloud.githubusercontent.com/assets/20953473/22789290/84ea77d2-eeb0-11e6-8648-a71236908a2f.png)
![screen shot 2017-02-09 at 10 09 12 am](https://cloud.githubusercontent.com/assets/20953473/22789292/84ef30e2-eeb0-11e6-98b9-a46c539c3ef2.png)

**Comment by alexlouden** [comment]
Ah interesting, thanks for letting me know! I'll have a look at fixing it on the weekend, unless you'd like to have a look? When you get [into it](https://github.com/alexlouden/Terraform.tmLanguage/blob/master/Terraform.YAML-tmLanguage#L86) it's just regex!

**Comment by alexlouden** [comment]
Hey @alex-aver thanks again for reporting this, it should be fixed now. I've made a [new release](https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.9.0), which should be available to update to in a few hours.

![screen shot 2017-02-13 at 10 57 16 am](https://cloud.githubusercontent.com/assets/1332954/22869605/68468c0a-f1db-11e6-9fe7-dab055cefa4a.png)

**Comment by alex-aver** [comment]
@alexlouden I didn't get a chance to look for replies until now, and what prompted me to do so was the fact that this was suddenly working! Thanks for this!

**Comment by alexlouden** [comment]
No worries, glad it's working for you!
