### ISSUE TITLE
Add syntax support when using heredoc

### ISSUE THREAD

**Issue by ApsOps** [alexlouden/Terraform.tmLanguage#20]

**Comment by alexlouden** [comment]
Good idea, thanks for the suggestion! I'll add it to the list.

**Comment by alexlouden** [comment]
See screenshot:
<img width="362" alt="screen shot 2017-03-08 at 4 41 05 pm" src="https://cloud.githubusercontent.com/assets/1332954/23696308/15788b36-041e-11e7-95a5-bfe3d1933823.png">

**Comment by alexlouden** [comment]
Just made a release: https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.11.0

**Comment by ApsOps** [comment]
Works as expected. Thanks!
