### ISSUE TITLE
Syntax highlight broken with braces not part of a terraform variable declaration

### ISSUE THREAD

**Issue by CloudNiner** [alexlouden/Terraform.tmLanguage#21]
Using version 0.10.0, it appears that syntax highlighting breaks when there are braces that are not part of a Terraform variable declaration. The braces in the regex are the offender here. 
```
resource "aws_alb_target_group" "pfb_app_http" {
  # Name can only be 32 characters long, so we MD5 hash the name and
  # truncate it to fit.
  name = "tf-alb-${replace("${md5("${var.environment}HTTPAppServer")}", "/(.{0,26})(.*)/", "$1")}"

  health_check {
    healthy_threshold   = "3"
    interval            = "60"
    matcher             = "301"
    protocol            = "HTTP"
    timeout             = "3"
    path                = "/"
    unhealthy_threshold = "2"
  }

  port     = "80"
  protocol = "HTTP"
  vpc_id   = "${module.vpc.id}"

  tags {
    Name        = "tg${var.environment}HTTPAppServer"
    Project     = "${var.project}"
    Environment = "${var.environment}"
  }
}
```

![screen shot 2017-03-06 at 08 19 49](https://cloud.githubusercontent.com/assets/1818302/23611509/bfcc9454-0245-11e7-80fe-1b222f457905.png)

**Comment by alexlouden** [comment]
Thanks for reporting this! I'll add it to the list, and let you know when it's fixed.

**Comment by alexlouden** [comment]
Hey CloudNiner, thanks again for taking the time to report this. I've fixed the bug and made a few changes to how string interpolation is matched, to hopefully make builtin functions and vars a bit clearer:

![screen shot 2017-03-30 at 9 57 09 pm](https://cloud.githubusercontent.com/assets/1332954/24507771/fc5a12f0-1593-11e7-9f48-4552aa1792bc.png)

What do you think?

**Comment by CloudNiner** [comment]
Looks great! Thanks for taking a look.

**Comment by alexlouden** [comment]
Great! I've made a [new release](https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.12.0) which you should get automatically upgraded to - please let me know if you have any more issues 👍
