### ISSUE TITLE
0.12.0 error

### ISSUE THREAD

**Issue by th7** [alexlouden/Terraform.tmLanguage#22]
> Error loading syntax file "Packages/Terraform.tmLanguage/Terraform.tmLanguage": Error in regex: empty range in char class in regex ([\w-\/\._\\%]+)

Using Sublime Text 2 Version 2.0.2, Build 2221

**Comment by alexlouden** [comment]
Ah sorry about that, I'll fix it today.

**Comment by alexlouden** [comment]
Hey @th7 I've put out a [new version](https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.12.1) with a fix - would you mind checking it fixes the bug? It works on the latest ST2 and ST3 for me.

**Comment by th7** [comment]
Hey! Sorry about the slow response. It looks great, thanks for your work on this!

**Comment by alexlouden** [comment]
@th7 No worries, glad you like it!
