### ISSUE TITLE
Syntax highlighting bugged using here doc

### ISSUE THREAD

**Issue by gertjanmaas** [alexlouden/Terraform.tmLanguage#23]
When using here doc syntax and the end of the here doc has whitespace before it, the syntax highlighting is wrong.

Whitespaces before EOF:
<img width="559" alt="screen shot 2017-04-10 at 08 20 40" src="https://cloud.githubusercontent.com/assets/2847704/24848349/a62652e6-1dc6-11e7-8eea-47f05ea8e50e.png">

No whitespace before EOF:
<img width="554" alt="screen shot 2017-04-10 at 08 20 52" src="https://cloud.githubusercontent.com/assets/2847704/24848353/ab1c6dbc-1dc6-11e7-9c1a-e62761cb2e06.png">

**Comment by alexlouden** [comment]
Hey @gertjanmaas thanks for reporting this! I think it should be a pretty quick fix - it looks like the [end regex](https://github.com/alexlouden/Terraform.tmLanguage/blob/master/Terraform.YAML-tmLanguage#L85) is `^\1$` and just needs to be `^\s*\1$` to handle preceding whitespace. I'll make the change when I can, hopefully one evening this week or on the weekend.
