### ISSUE TITLE
Incorrect colors applied to parentheses in nested function calls

### ISSUE THREAD

**Issue by fabiendelpierre** [alexlouden/Terraform.tmLanguage#26]
Hi there,
I'm using v0.13.0 of your highlighter and I believe I found a minor bug in the way colors are applied in a particular scenario, example screencap here:
![screenshot](http://i.imgur.com/BfA5g36.png)
In the `md5(timestamp())` bit on the right, I don't think the right paren in `timestamp()` should be orange. In case it matters, this is in an `aws_rds_cluster` resource. Let me know if you have any questions!

**Comment by alexlouden** [comment]
Hey Fabien,

Thanks for reporting this! I think it's just ignoring the 'timestamp' function so it's matching the first closing bracket - should be an easy fix. I'll let you know when I've fixed it and put out a new release. 

Thanks,
Alex

**Comment by fabiendelpierre** [comment]
👍

**Comment by alexlouden** [comment]
Hey Fabien,

I've put out a [fix](https://github.com/alexlouden/Terraform.tmLanguage/commit/b5b9a75ca3e3167c90ccd5b2e40a37b18ee111de) which works for me - could you give it a shot when your Sublime has updated to the [latest version](https://github.com/alexlouden/Terraform.tmLanguage/releases/tag/0.13.1)?

<img width="333" alt="screen shot 2017-08-11 at 11 23 25 am" src="https://user-images.githubusercontent.com/1332954/29198497-c6343360-7e87-11e7-95ae-d766a26834f1.png">

Cheers,
Alex

**Comment by fabiendelpierre** [comment]
Looks good to me now, thank you!
