### ISSUE TITLE
Highlight doesn't support 2.31 AWS provider syntax on TF 12.16

### ISSUE THREAD

**Issue by c240amg** [alexlouden/Terraform.tmLanguage#40]
Using terraform (0.12.16) validate returns the below:

> 
> **Warning: Quoted references are deprecated**
> 
>   on 20_subnet.tf line 4, in resource "aws_subnet" "subnet-core":
>    4:   depends_on = ["aws_vpc.workbench"]
> 
> In this context, references are expected literally rather than in quotes.
> Terraform 0.11 and earlier required quotes, but quoted references are now
> deprecated and will be removed in a future version of Terraform. Remove the
> quotes surrounding this reference to silence this warning.
> 
> 
> **Warning: Interpolation-only expressions are deprecated**
> 
>   on 20_subnet.tf line 6, in resource "aws_subnet" "subnet-core":
>    6:   count = "${length(var.core_subnet)}"
> 
> Terraform 0.11 and earlier required all non-constant expressions to be
> provided via interpolation syntax, but this pattern is now deprecated. To
> silence this warning, remove the "${ sequence from the start and the }"
> sequence from the end of this expression, leaving just the inner expression.
> 
> Template interpolation syntax is still used to construct strings from
> expressions when the template includes multiple interpolation sequences or a
> mixture of literal strings and interpolations. This deprecation applies only
> to templates that consist entirely of a single interpolation sequence.
> 
When correcting them from:
count = "${length(var.core_subnet)}"
to:
count = length(var.core_subnet)

it doesn't highlight it correctly, and only leaves it white.

**Comment by c240amg** [comment]
Another example:

> Warning: Quoted type constraints are deprecated
> 
>   on 00_variables.tf line 137, in variable "CloudinitscriptPath":
>  137:   type    = "string"
> 
> Terraform 0.11 and earlier required type constraints to be given in quotes,
> but that form is now deprecated and will be removed in a future version of
> Terraform. To silence this warning, remove the quotes around "string".
>

**Comment by patrickrgaffney** [comment]
This is fixed as of #39 — please upgrade to v1.0.0. Let us know if you run into any other issues.

<img width="416" alt="Screen Shot 2020-01-20 at 12 19 11 AM" src="https://user-images.githubusercontent.com/7366232/72703172-8680d500-3b1a-11ea-99ea-f6cbeda84567.png">
