### ISSUE TITLE
Release a 1.1.0 version

### ISSUE THREAD

**Issue by petems** [alexlouden/Terraform.tmLanguage#45]
Would be nice to have a 1.1.0 release cut, so we can remove the quotes around snippets for TF 0.12 >= (#42)

https://github.com/alexlouden/Terraform.tmLanguage/compare/1.0.0...master

**Comment by radeksimko** [comment]
Just published the tag & created relevant GitHub release, but I'm not sure if there's anything else to be done in terms of release distribution to users - @alexlouden ?

**Comment by alexlouden** [comment]
That’s it! It should become available within a few hours ☺️

--  
Alex
