### ISSUE TITLE
Use this repo to add Terraform Syntax Highlighting to GitHub?

### ISSUE THREAD

**Issue by phinze** [alexlouden/Terraform.tmLanguage#5]
Hi there @alexlouden - thanks for putting this together!

I believe we can use this as a stepping stone to potentially getting .tf files highlighted on GitHub's web interface.

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

I don't have time to look into it further at the moment, but I just wanted to call this out as a possibility. :grinning:

**Comment by alexlouden** [comment]
Sounds like a great idea - I'm not using Terraform at the moment and don't have time to pursue this, but I'd welcome contributions!

**Comment by alexlouden** [comment]
Hoping to make a bit of progress on this - see the linked issue

**Comment by alexlouden** [comment]
@phinze Took a few months, but just got my branch merged into master! 🎉  Not sure when it'll be released.

**Comment by alexlouden** [comment]
Closed - looks like it's live!
